services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist/apps/jobie-ui:/usr/share/nginx/html:ro
    depends_on:
      - api-gateway

  api-gateway:
    build:
      context: ./dist/apps/api-gateway
    container_name: api-gateway
    environment:
      - USE_AUTH=false
    dockerfile: ./Dockerfile
    env_file:
      - .env.deployment
    expose:
      - '3000'

  user-profile-enrichment:
    build:
      context: ./dist/apps/user-profile-enrichment
    container_name: user-profile-enrichment
    env_file:
      - .env.deployment
    dockerfile: ./Dockerfile
    expose:
      - '3001'

  roadmap-calibration:
    build:
      context: ./dist/apps/roadmap-calibration
    container_name: roadmap-calibration
    env_file:
      - .env.deployment
    dockerfile: ./Dockerfile
    expose:
      - '3002'

  milestone-management:
    build:
      context: ./dist/apps/milestone-management
    container_name: milestone-management
    env_file:
      - .env.deployment
    dockerfile: ./Dockerfile
    expose:
      - '3003'
