version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist/apps/jobie-ui:/usr/share/nginx/html:ro
    depends_on:
      - api-gateway
      - user-profile-enrichment
      - roadmap-calibration

  api-gateway:
    build:
      context: ./dist/apps/api-gateway
    container_name: api-gateway
    expose:
      - '3000'

  user-profile-enrichment:
    build:
      context: ./dist/apps/user-profile-enrichment
    container_name: user-profile-enrichment
    expose:
      - '3001'

  roadmap-calibration:
    build:
      context: ./dist/apps/roadmap-calibration
    container_name: roadmap-calibration
    expose:
      - '3002'
