services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    restart: always
    command: 'nginx -g "daemon off;"'
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist/apps/jobie-ui:/usr/share/nginx/html:ro
    depends_on:
      - api-gateway

  api-gateway:
    build:
      context: ./dist/apps/api-gateway
      dockerfile: ../../../Dockerfile
      args:
        - SERVICE_PORT=3000
    container_name: api-gateway
    restart: always
    environment:
      - USE_AUTH=false
      - PORT=3000
    env_file:
      - .env.deployment
    expose:
      - '3000'

  user-profile-enrichment:
    build:
      context: ./dist/apps/user-profile-enrichment
      dockerfile: ../../../Dockerfile
      args:
        - SERVICE_PORT=3001
    container_name: user-profile-enrichment
    restart: always
    environment:
      - PORT=3001
    env_file:
      - .env.deployment
    expose:
      - '3001'

  roadmap-calibration:
    build:
      context: ./dist/apps/roadmap-calibration
      dockerfile: ../../../Dockerfile
      args:
        - SERVICE_PORT=3002
    container_name: roadmap-calibration
    restart: always
    environment:
      - PORT=3002
    env_file:
      - .env.deployment
    expose:
      - '3002'

  milestone-management:
    build:
      context: ./dist/apps/milestone-management
      dockerfile: ../../../Dockerfile
      args:
        - SERVICE_PORT=3003
    container_name: milestone-management
    restart: always
    environment:
      - PORT=3003
    env_file:
      - .env.deployment
    expose:
      - '3003'
